Update tdei-api.json
TaskarCenterAtUW/TDEI-ExternalAPIs pull request #12
Opened 2023-01-13 21:11 UTC by kristinann

Modified the descriptions for the InvalidRequest and UnauthorizedRequest responses.

2023-01-13 23:56 UTC, sureshgaussian requested changes

2023-01-13 23:56 UTC, sureshgaussian commented on tdei-api.json
> +                "description": "This request is unauthorized. The AppID or Authorization Token provided is not authorized to perform this request."
Should we change this to "This request is unauthorized. The API_KEY or the authorization token provided is invalid to perform this request"?

2023-01-13 23:57 UTC, kristinann commented
Yes, please. Thanks for the catch.

------------------------------------------

Kristin Tufte, PhD (she/her)
Transportation Data Equity Initiative (TDEI)
TRAC/TCAT
University of Washington
***@***.***

From: Suresh ***@***.***>
Date: Friday, January 13, 2023 at 3:57 PM
To: TaskarCenterAtUW/TDEI-ExternalAPIs ***@***.***>
Cc: Kristin A Tufte ***@***.***>, Author ***@***.***>
Subject: Re: [TaskarCenterAtUW/TDEI-ExternalAPIs] Update tdei-api.json (PR #12)

@sureshgaussian requested changes on this pull request.

________________________________

In tdei-api.json<https://urldefense.com/v3/__https:/github.com/TaskarCenterAtUW/TDEI-ExternalAPIs/pull/12*discussion_r1070167604__;Iw!!K-Hz7m0Vt54!n_xd2g_5UIZAlexIGF86w3hCpvKV-ECGA63NIn3lJu3_F0mOlcPpyZktDsN5ZqvlaaimxEjm7hTfUstQqZCKoA$>:

> @@ -1706,7 +1706,7 @@

         },

         "responses": {

             "Unauthorized": {

-                "description": "This request is unauthorized. appID is invalid. Please obtain a valid application ID (appID)."

+                "description": "This request is unauthorized. The AppID or Authorization Token provided is not authorized to perform this request."

Should we change this to "This request is unauthorized. The API_KEY or the authorization token provided is invalid to perform this request"?

—
Reply to this email directly, view it on GitHub<https://urldefense.com/v3/__https:/github.com/TaskarCenterAtUW/TDEI-ExternalAPIs/pull/12*pullrequestreview-1248669539__;Iw!!K-Hz7m0Vt54!n_xd2g_5UIZAlexIGF86w3hCpvKV-ECGA63NIn3lJu3_F0mOlcPpyZktDsN5ZqvlaaimxEjm7hTfUsswhpdCQg$>, or unsubscribe<https://urldefense.com/v3/__https:/github.com/notifications/unsubscribe-auth/AABDJQH6GQ5TL5HOJWPSFG3WSHTU5ANCNFSM6AAAAAAT22JMAU__;!!K-Hz7m0Vt54!n_xd2g_5UIZAlexIGF86w3hCpvKV-ECGA63NIn3lJu3_F0mOlcPpyZktDsN5ZqvlaaimxEjm7hTfUsvDQeW9uA$>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-01-14 00:11 UTC, sureshgaussian approved these changes

2023-01-14 00:11 UTC, merged